import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Header from '../components/Header';
import Nav from '../components/Nav';

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html>
        <body>
        <Header/>
        <Nav/>
        <div className={'pl-[16.6666666667%] h-screen w-full bg-gray-200'}>
            {children}
        </div>
        </body>
        </html>
    )
}


// // pages/index.tsx
// import React from 'react';
// import Header from '../components/Header';
// import PostList from '../components/PostList';
// import {Post as PostType} from '../types/post';
//
// const posts: PostType[] = [
//     {id: 1, title: 'Post 1', content: 'Content of post 1'},
//     {id: 2, title: 'Post 2', content: 'Content of post 2'},
//     {id: 3, title: 'Post 3', content: 'Content of post 3'},
// ];
//
// const Home: React.FC = () => (
//     <div>
//
//         <h1>Welcome to My Blog</h1>
//
//     </div>
// );
//
// export default Home;
